myStr : string = 
    '<div class="hero-body">' + LineEnding + 
    '    <div class="container has-text-centered">' + LineEnding + 
    '        <div class="column is-6 is-offset-3">' + LineEnding + 
    '            <h1 class="title">' + LineEnding + 
    '                {{ username }}' + LineEnding + 
    '            </h1>' + LineEnding + 
    '        </div>' + LineEnding + 
    '    </div>' + LineEnding + 
    '</div>';
