(*!------------------------------------------------------------
 * Fano CLI Application (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano-cli
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano-cli/blob/master/LICENSE (MIT)
 *------------------------------------------------------------- *)

{%fanocli.pas}

{$INCLUDE Info/task.registrations.inc}
{$INCLUDE Project/task.registrations.inc}
{$INCLUDE ProjectNoGit/task.registrations.inc}
{$INCLUDE ProjectNoCommit/task.registrations.inc}
{$INCLUDE Controller/task.registrations.inc}
