(*!------------------------------------------------------------
 * Fano CLI Application (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano-cli
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano-cli/blob/master/LICENSE (MIT)
 *------------------------------------------------------------- *)

{%fanocli.pas}

{$INCLUDE Info/task.registrations.inc}
{$INCLUDE KeyGen/task.registrations.inc}
{$INCLUDE GuidGen/task.registrations.inc}
{$INCLUDE Project/task.registrations.inc}
{$INCLUDE Controller/task.registrations.inc}
{$INCLUDE View/task.registrations.inc}
{$INCLUDE Model/task.registrations.inc}
{$INCLUDE Mvc/task.registrations.inc}
{$INCLUDE Middleware/task.registrations.inc}
{$INCLUDE Deploy/task.registrations.inc}
{$INCLUDE Minifier/task.registrations.inc}
{$INCLUDE Daemon/task.registrations.inc}
