(*!------------------------------------------------------------
 * Fano CLI Application (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano-cli
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano-cli/blob/master/LICENSE (MIT)
 *------------------------------------------------------------- *)

DeployCgiTaskFactoryImpl,
XDeployCgiTaskFactoryImpl,
DeployFcgiTaskFactoryImpl,
DeployFcgidTaskFactoryImpl,
DeployScgiTaskFactoryImpl,
DeployUwsgiTaskFactoryImpl,
DeployHttpTaskFactoryImpl,
DeployScgiBalancerTaskFactoryImpl,
DeployFcgiBalancerTaskFactoryImpl,
DeployUwsgiBalancerTaskFactoryImpl,
DeployHttpBalancerTaskFactoryImpl,
