(*!------------------------------------------------------------
 * Fano CLI Application (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano-cli
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano-cli/blob/master/LICENSE (MIT)
 *------------------------------------------------------------- *)

{$INCLUDE Apps/Includes/units.inc}
{$INCLUDE Libs/Includes/units.inc}
{$INCLUDE Tasks/Includes/contracts.inc}
{$INCLUDE Tasks/Includes/units.inc}
