(*!------------------------------------------------------------
 * Fano CLI Application (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano-cli
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano-cli/blob/master/LICENSE (MIT)
 *------------------------------------------------------------- *)

{%fanocli.pas}

{$INCLUDE Core/task.registrations.inc}
{$INCLUDE Cgi/task.registrations.inc}
{$INCLUDE FastCgi/task.registrations.inc}
{$INCLUDE Scgi/task.registrations.inc}
{$INCLUDE Uwsgi/task.registrations.inc}
{$INCLUDE Fcgid/task.registrations.inc}
{$INCLUDE NoGit/task.registrations.inc}
{$INCLUDE NoCommit/task.registrations.inc}
