(*!------------------------------------------------------------
 * Fano CLI Application (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano-cli
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano-cli/blob/master/LICENSE (MIT)
 *------------------------------------------------------------- *)

CreateProjectDependenciesTaskFactoryImpl,
CreateAppBootstrapTaskFactoryImpl,
CreateAppBootstrapScgiTaskFactoryImpl,
CreateAppBootstrapFcgiTaskFactoryImpl,
CreateAppBootstrapFcgidTaskFactoryImpl,
CreateAppBootstrapUwsgiTaskFactoryImpl,
CreateAppBootstrapMhdTaskFactoryImpl,
CreateProjectTaskFactoryImpl,
CreateDaemonProjectTaskFactoryImpl,
