strGitignore: string = 
    'app/config/config.json'+#13#10+
    'app/public/.htaccess'+#13#10+
    'app/public/app.cgi'+#13#10+
    'app/cgi-bin/app.cgi'+#13#10+
    'app/storages/logs/*'+#13#10+
    '!app/storages/logs/README.md'+#13#10+
    'build.cfg'+#13#10+
    'build.dev.cfg'+#13#10+
    'build.prod.cfg'+#13#10+
    'bin/unit/*'+#13#10+
    '!bin/README.md'+#13#10+
    '!bin/unit/README.md'+#13#10+
    'fp.dir';
